OLED support
forkineye/ESPixelStick pull request #729
Opened 2024-01-14 23:45 UTC by noman1228

Just env lib and main loop.

2024-01-15 13:48 UTC, MartinMueller2003 commented on platformio.ini
Why did the header get removed?
Why are you adding an extra Platform type?

2024-01-15 13:50 UTC, MartinMueller2003 commented on ESPixelStick/ESPixelStick.ino
> -/*
Please restore the headings 
Please restore the formatting. You removed much of the indenting. Please keep your changes to a minimum.

2024-01-15 13:53 UTC, MartinMueller2003 commented on ESPixelStick/ESPixelStick.ino
> +// OLED
Please create an OLED file and move all of this to that file. Please make the entire file contents conditional (look at the temperature sensor setup). Then enable this in your platform.

2024-01-15 13:54 UTC, MartinMueller2003 commented on ESPixelStick/ESPixelStick.ino
> +const String VERSION = "4.x-jmt";
Please restore this line. This is done using the platform name from platformio.ini

2024-01-15 13:54 UTC, forkineye requested changes
On top of what Martin has already noted, you deleted all the distribution and documentation files.

2024-01-15 13:55 UTC, MartinMueller2003 commented on ESPixelStick/ESPixelStick.ino
> +int period = 5000;
These should not be here. Please move to the oled file.

2024-01-15 13:59 UTC, MartinMueller2003 commented on ESPixelStick/ESPixelStick.ino
> +            ; // Don't proceed, loop forever
We never loop forever. If it does not work, then print out a message and keep going. The oled is not a critical resource for operation. If you want to for a reboot then set the reboot request flag and move on.

2024-01-15 14:04 UTC, MartinMueller2003 commented on ESPixelStick/ESPixelStick.ino
> +
Please restore this code.

2024-01-15 14:05 UTC, MartinMueller2003 commented on ESPixelStick/ESPixelStick.ino
> +    if(millis() >= time_now + period){
Move this call to the oled files and make a call that is conditionally compiled.

2024-01-15 14:06 UTC, MartinMueller2003 commented on ESPixelStick/src/ESPixelStick.h
> +
Please dont change the formatting

2024-01-15 14:08 UTC, MartinMueller2003 commented on ESPixelStick/src/GPIO_Defs.hpp
> +#   include "platformDefinitions/GPIO_Defs_ESP32_DevKitv1-JMT.hpp"
Is this really needed?

2024-01-15 14:11 UTC, MartinMueller2003 commented on ESPixelStick/src/platformDefinitions/GPIO_Defs_ESP32_DevkitC.hpp
> +// File Manager - FIXED JMT
Please dont add such identifiers to the source code. Git blame provides this without cluttering up code.

2024-01-15 14:12 UTC, MartinMueller2003 commented on SupportingDocs/FSEQ_Sequence_File_Format.txt
> -v1.0 spec
Why are these files being deleted?

2024-01-15 14:19 UTC, MartinMueller2003 commented
I have reached my single review comment limit. 
Please undo all of the format changes. They make doing a review difficult.
Please restore the missing files and restructure your oled support into an oled class. The class should be stand alone and technology independent. you can create a sub class for the specific oled you are implementing. Keen in mind that others may want to use other oled devices so your flavor should be a derived class from a pure virtual base class and the base class is used by the ino file.

2024-01-15 14:21 UTC, MartinMueller2003 commented
And please use useful commit comments.

2024-01-15 17:00 UTC, forkineye commented
Closing this one due to the numerous issues.  Feel free to re-submit once they're corrected.

2024-01-15 17:00 UTC, closed without merging

2024-01-18 21:26 UTC, noman1228 commented
Re-Forking and instituting minimal changes with conditional includes. Told you it was hacky.... Thanks for your patience and hard work!